# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: f:/FPGA/shudianshiyan/simple_mcu_test/simple_mcu_test.srcs/sources_1/ip/verify_RAM/verify_RAM.xci
# IP: The module: 'verify_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA/shudianshiyan/simple_mcu_test/simple_mcu_test.gen/sources_1/ip/verify_RAM/verify_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'verify_RAM'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet

# IP: f:/FPGA/shudianshiyan/simple_mcu_test/simple_mcu_test.srcs/sources_1/ip/verify_RAM/verify_RAM.xci
# IP: The module: 'verify_RAM' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: f:/FPGA/shudianshiyan/simple_mcu_test/simple_mcu_test.gen/sources_1/ip/verify_RAM/verify_RAM_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'verify_RAM'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells U0 -quiet] -quiet
