# This file is automatically generated.
# It contains project source information necessary for synthesis and implementation.

# IP: E:/workspace/HDL/00YingCai/Test/class3/class_routine/ALU_FULL/ALU_stu.srcs/sources_1/ip/sys_clk/sys_clk.xci
# IP: The module: 'sys_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/workspace/HDL/00YingCai/Test/class3/class_routine/ALU_FULL/ALU_stu.gen/sources_1/ip/sys_clk/sys_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/workspace/HDL/00YingCai/Test/class3/class_routine/ALU_FULL/ALU_stu.gen/sources_1/ip/sys_clk/sys_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/workspace/HDL/00YingCai/Test/class3/class_routine/ALU_FULL/ALU_stu.gen/sources_1/ip/sys_clk/sys_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# IP: E:/workspace/HDL/00YingCai/Test/class3/class_routine/ALU_FULL/ALU_stu.srcs/sources_1/ip/sys_clk/sys_clk.xci
# IP: The module: 'sys_clk' is the root of the design. Do not add the DONT_TOUCH constraint.

# XDC: e:/workspace/HDL/00YingCai/Test/class3/class_routine/ALU_FULL/ALU_stu.gen/sources_1/ip/sys_clk/sys_clk_board.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/workspace/HDL/00YingCai/Test/class3/class_routine/ALU_FULL/ALU_stu.gen/sources_1/ip/sys_clk/sys_clk.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet

# XDC: e:/workspace/HDL/00YingCai/Test/class3/class_routine/ALU_FULL/ALU_stu.gen/sources_1/ip/sys_clk/sys_clk_ooc.xdc
# XDC: The top module name and the constraint reference have the same name: 'sys_clk'. Do not add the DONT_TOUCH constraint.
#dup# set_property KEEP_HIERARCHY SOFT [get_cells inst -quiet] -quiet
