webtalk_init -webtalk_dir F:/FPGA/shudianshiyan/simple_mcu_test/simple_mcu_test.sim/sim_1/behav/xsim/xsim.dir/tb_mcu_top_behav/webtalk/
webtalk_register_client -client project
webtalk_add_data -client project -key date_generated -value "Fri Jun  5 10:30:29 2026" -context "software_version_and_target_device"
webtalk_add_data -client project -key product_version -value "XSIM v2020.2 (64-bit)" -context "software_version_and_target_device"
webtalk_add_data -client project -key build_version -value "3064766" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_platform -value "WIN64" -context "software_version_and_target_device"
webtalk_add_data -client project -key registration_id -value "" -context "software_version_and_target_device"
webtalk_add_data -client project -key tool_flow -value "xsim_vivado" -context "software_version_and_target_device"
webtalk_add_data -client project -key beta -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key route_design -value "FALSE" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_family -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_device -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_package -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key target_speed -value "not_applicable" -context "software_version_and_target_device"
webtalk_add_data -client project -key random_id -value "4986081a-38a1-4c50-97c6-6a77dbb8e9e0" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_id -value "bdc1c0e0f0d2487eb4e3d79c632cb8d5" -context "software_version_and_target_device"
webtalk_add_data -client project -key project_iteration -value "5" -context "software_version_and_target_device"
webtalk_add_data -client project -key os_name -value "Windows Server 2016 or Windows 10" -context "user_environment"
webtalk_add_data -client project -key os_release -value "major release  (build 9200)" -context "user_environment"
webtalk_add_data -client project -key cpu_name -value "AMD Ryzen 7 8845H w/ Radeon 780M Graphics" -context "user_environment"
webtalk_add_data -client project -key cpu_speed -value "3793 MHz" -context "user_environment"
webtalk_add_data -client project -key total_processors -value "1" -context "user_environment"
webtalk_add_data -client project -key system_ram -value "16.000 GB" -context "user_environment"
webtalk_register_client -client xsim
webtalk_add_data -client xsim -key Command -value "xsim" -context "xsim\\command_line_options"
webtalk_add_data -client xsim -key trace_waveform -value "true" -context "xsim\\usage"
webtalk_add_data -client xsim -key runtime -value "1 us" -context "xsim\\usage"
webtalk_add_data -client xsim -key iteration -value "3" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Time -value "0.08_sec" -context "xsim\\usage"
webtalk_add_data -client xsim -key Simulation_Memory -value "23212_KB" -context "xsim\\usage"
webtalk_transmit -clientid 2666564954 -regid "" -xml F:/FPGA/shudianshiyan/simple_mcu_test/simple_mcu_test.sim/sim_1/behav/xsim/xsim.dir/tb_mcu_top_behav/webtalk/usage_statistics_ext_xsim.xml -html F:/FPGA/shudianshiyan/simple_mcu_test/simple_mcu_test.sim/sim_1/behav/xsim/xsim.dir/tb_mcu_top_behav/webtalk/usage_statistics_ext_xsim.html -wdm F:/FPGA/shudianshiyan/simple_mcu_test/simple_mcu_test.sim/sim_1/behav/xsim/xsim.dir/tb_mcu_top_behav/webtalk/usage_statistics_ext_xsim.wdm -intro "<H3>XSIM Usage Report</H3><BR>"
webtalk_terminate
